pipeline {
    agent {
       tools{
           maven '392'
       }
    }
    stages {
        stage('Clean Dir') {
            steps {
                deleteDir()  // This will clean the workspace
            }
        }
        stage('Clone Git') {
            steps {
                sh 'git clone https://github.com/sakula-1/simple-java-maven-app.git'
            }
        }
        stage('Maven version') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('Maven test') {
            steps {
                dir('simple-java-maven-app') { // Correct the directory path
                    sh 'mvn test' // Close the quote properly
                }
            }
        }
    stage('Maven build') {
            steps {
                sh 'mvn package'
            }
        }
    }
}
